### ISSUE TITLE
PayPal Mobile

### ISSUE THREAD

**Issue by qcasey** [akc3n/banking#127]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

PayPal Mobile

### Link to app

https://play.google.com/store/apps/details?id=com.paypal.android.p2pmobile

### App version

8.23.0

### Country of the app

United States 

### Build Number

SQ3A.220705.004.2022081800

### Device

- [ ] Pixel 6a
- [X] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [ ] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [ ] Works
- [ ] Does not work
- [X] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

This one surprised me, as PayPal hasn't been working on Microg based phones for months. It crashes on the splash screen. 

On GOS the app works. Every part of the ui seems to work, send/request payments, fingerprint login. I haven't tested scan to pay but the camera loads up.

**Comment by akc3n** [comment]
This is a really good point to add this. As many people do use this. Just never thought of it. Thanks @qcasey

**Comment by tommytran732** [comment]
Paypal stopped working so I am removing it from the list for the time being.

**Comment by akc3n** [comment]
@tommytran732 I feel that a lot of banking apps will stop working once they switch over to the play integrity api.

I have a dm on matrix stating that HSBC no longer works either

**Comment by qcasey** [comment]
PayPal still works on my device, version 8.28.1 on TD1A.220804.031.2022102600. Although I'm counting down the days

**Comment by akc3n** [comment]
> PayPal still works on my device, version 8.28.1 on TD1A.220804.031.2022102600. Although I'm counting down the days

Thank you. Will update the list shortly.

**Comment by Marocco2** [comment]
On GrapheneOS, it will pop up 2FA every time you open PayPal app compared to stock OS: https://discuss.grapheneos.org/d/2746-paypal-sca

**Comment by Youngblood50** [comment]
Apoarently PayPal started using Play Integrity, the Play Store now says that the app is incompatible. At least on GrapheneOS, Android 15, Pixel 8 Pro

**Comment by spring-onion** [comment]
I can't reproduce this on a pixel 7a build 2024102100.

**Comment by Youngblood50** [comment]
> I can't reproduce this on a pixel 7a build 2024102100.

ok so i have a theory: do you have google services framework installed?

**Comment by Marocco2** [comment]
> Apparently PayPal started using Play Integrity, the Play Store now says that the app is incompatible. At least on GrapheneOS, Android 15, Pixel 8 Pro. You are still able to install the app from Aurora Store and still works.

I've opened it rn but it crashes for some reason:
```
type: crash
osVersion: google/husky/husky:15/AP3A.241005.015/2024102100:user/release-keys
flags: dev options enabled
package: com.paypal.android.p2pmobile:1150082604
process: com.paypal.android.p2pmobile
processUptime: 452 + 219 ms
installer: com.android.vending

java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.RuntimeException: 0
	at android.app.ActivityThread.installProvider(ActivityThread.java:8328)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7838)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7519)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2423)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8736)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.RuntimeException: 0
	at com.google.firebase.provider.FirebaseInitProvider.onCreate(:1565)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2644)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2613)
	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(:61)
	at android.app.ActivityThread.installProvider(ActivityThread.java:8323)
	... 13 more
```

**Comment by Marocco2** [comment]
> @Marocco2 Disable developer settings.

Still crashes:
```
type: crash
osVersion: google/husky/husky:15/AP3A.241005.015/2024102100:user/release-keys
package: com.paypal.android.p2pmobile:1150082604
process: com.paypal.android.p2pmobile
processUptime: 693 + 344 ms
installer: com.android.vending

java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.RuntimeException: 0
	at android.app.ActivityThread.installProvider(ActivityThread.java:8328)
	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7838)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7519)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2423)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8736)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
Caused by: java.lang.RuntimeException: 0
	at com.google.firebase.provider.FirebaseInitProvider.onCreate(:1565)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2644)
	at android.content.ContentProvider.attachInfo(ContentProvider.java:2613)
	at com.google.firebase.provider.FirebaseInitProvider.attachInfo(:61)
	at android.app.ActivityThread.installProvider(ActivityThread.java:8323)
	... 13 more
```

**Comment by Marocco2** [comment]
Following my comments, PayPal now starts if I allow Native code debugging

**Comment by spring-onion** [comment]
@Youngblood50 Ahh alright, thanks for sharing!
@Marocco2 Glad you got it working again.

**Comment by gamiel-7-2** [comment]
Paypal still works on my device, version 8.90.1 on grapheneOS build number 2025090800, Android 16, on a Google Pixel 9

**Comment by C0D3-M4513R** [comment]
I was able to install paypal from the google play store as usual too after a couple of attempts.

But Paypal also sometimes seems to check the integrity api when logging in and then denies biometrics (password & 2fa still work tho). Other times it just doesn't check integrity.

Using Pixel 9a

**Comment by mp21-org** [comment]
App Crashes since the last update. Resetting storage data also didn't help. Crash Log attached.

[Error in PayPal afeebeab092d.txt](https://github.com/user-attachments/files/31406031/Error.in.PayPal.afeebeab092d.txt)

Also using a Pixel 9a.

EDIT: Problematic version is v10.10.0 (1160090162)

**Comment by C0D3-M4513R** [comment]
@mp21-org Disabling Secure App Spawning for Paypal seems to solve this issue.

**Comment by michaelbeaumont** [comment]
On GrapheneOS/Pixel 10a without Google Play Services, PayPal works fine EXCEPT NFC/Pay, which works fine _with_ Google Play Services. Tested in secondary profile

**Comment by alicela1n** [comment]
PayPal crashes on my Pixel 10A running Graphene even if I disable Secure app spawning

**Comment by periodicdesign** [comment]
On GrapheneOS/Pixel 10a **with** Google Play Services and the app is crashing.
- Version 10.13.0
- Mixture of process exited due to signal 9 and earlier it was a failed security check
