### ISSUE TITLE
After updating to Android 13, has anyone experienced any sort of problem(s) with specific functions of their banking app?

### ISSUE THREAD

**Issue by akc3n** [akc3n/banking#130]
I was just wondering if anyone had encountered any specific problem(s) that might be disrupting a feature (or features) usage within their banking app.

After updating to Android 13, an user reported on our OS-Issue-Tracker that they were unable to complete a wire transfer using their banking app.

re: https://github.com/GrapheneOS/os-issue-tracker/issues/1431

> With the last update to Android 12 i get a android system password prompt when trying to make a wire transfer with my Vivid banking app. When i put in the system password the banking app shows an error and doesn't do the wire transfer. With the old Android Version there was a in-app pin input which worked fine.

**Comment by bungabunga** [comment]
Hi,

after upgrading to Android 13 my banking NFC payment app crashes immediately after opening it.

this is what I was able to collect from the crash:

type: crash
osVersion: google/oriole/oriole:13/TP1A.220624.021/2022082400:user/release-keys
package: si.nlbpay.slovenija:40704
process: si.nlbpay.slovenija

java.lang.RuntimeException: Unable to create application com.vipera.mwalletintegration.ProtectedPaymentApplication: com.vipera.mwalletintegration.MessageGuardException_RFA6IDEwMyBbMjAyMjAxMTEtMjAyMjAyMjUxMDU5IFsrKysrKytdIGFybTY0OmFybTY0LXY4YSAzMyBnb29nbGUvb3Jpb2xlL29yaW9sZToxMy9UUDFBLjIyMDYyNC4wMjEvMjAyMjA4MjQwMDp1c2VyL3JlbGVhc2Uta2V5c10: DP: 103
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6796)
at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2135)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7904)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ExecInit.main(ExecInit.java:48)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
Caused by: com.vipera.mwalletintegration.MessageGuardException_RFA6IDEwMyBbMjAyMjAxMTEtMjAyMjAyMjUxMDU5IFsrKysrKytdIGFybTY0OmFybTY0LXY4YSAzMyBnb29nbGUvb3Jpb2xlL29yaW9sZToxMy9UUDFBLjIyMDYyNC4wMjEvMjAyMjA4MjQwMDp1c2VyL3JlbGVhc2Uta2V5c10: DP: 103
at com.vipera.mwalletintegration.ProtectedPaymentApplication.lonBEIji(Unknown Source:4)
at com.vipera.mwalletintegration.ProtectedPaymentApplication.onCreate(Unknown Source:44)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1271)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6791)
... 11 more
Caused by: java.lang.RuntimeException: DP: 103
at com.vipera.mwalletintegration.ProtectedPaymentApplication.bmaBkd(Native Method)
at java.lang.reflect.Method.invoke(Native Method)
at com.vipera.mwalletintegration.ProtectedPaymentApplication$HCEIntegrationPlugin$d.r(Unknown Source:31)
at com.vipera.mwalletintegration.ProtectedPaymentApplication$HCEIntegrationPlugin$d.cnbgtrJh(Unknown Source:472)
at com.vipera.mwalletintegration.ProtectedPaymentApplication.bmaBkd(Native Method)
at com.vipera.mwalletintegration.ProtectedPaymentApplication.onCreate(Unknown Source:39)
... 13 more

**Comment by akc3n** [comment]
@bungabunga I did attempt to get this sorted several times on my own. Had no luck  due to very limited experience with logcat and next to none on the development side of things. 
I will addressing that point specifically and formally in a properly structured README.md and with full transparency in regards to my ability, or lack there of, to handle users logcat issues that have been coming in since Android 13 upgrade.  This way at least you're not all waiting around and counting on something I can not deliver on myself. Thank you for you patients, and apologizes, sincerely. However, with no issues after the upgrade may still submit app reports if they wish.

Here are some general solutions that have worked for other uses w
1. Check to see if you have native

**Comment by akc3n** [comment]
@bungabunga with this new merge on to PrivSec, hopefully we can provide some help with logcat reports as time permits.
