### ISSUE TITLE
Deutsche Bank Mobile -- Germany

### ISSUE THREAD

**Issue by ljrk0** [akc3n/banking#38]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### App name

Deutsche Bank

### Link to app

https://play.google.com/store/apps/details?id=com.db.pwcc.dbmobile

### App version

1.23.0

### Country of the app

Germany

### Device

- [ ] Pixel 6 Pro
- [ ] Pixel 6
- [ ] Pixel 5a
- [ ] Pixel 5
- [ ] Pixel 4a (5G)
- [X] Pixel 4a
- [ ] Pixel 4 XL
- [ ] Pixel 4
- [ ] Pixel 3a XL
- [ ] Pixel 3a
- [ ] Pixel 3 XL
- [ ] Pixel 3

### Google Play installed

- [X] Installed
- [ ] Not installed

### Google Play services Network permission revoked?

- [ ] Revoked
- [X] Not revoked
- [ ] I did not have Google Play services installed

### SafetyNet Enforcement

- [ ] Enforced
- [ ] Not enforced
- [X] Unsure

### Native code debugging

- [X] Enabled
- [ ] Disabled

### Stock OS compatibility

- [ ] Works
- [ ] Does not work
- [X] Not tested

### Profile app tested in

- [X] Main user profile
- [ ] Secondary user profile
- [ ] I used a work profile device manager app (Please mention more details about it down below like the app)

### Description of the app's functionality

Works:

* Overview/Management of recurring payments
* Money transfers
* Everything else done usually in the web interface that supported in-app

Doesn't Work:

* Activating Mobile Payment (hangs)

### ADB logcat of the app if necessary

Stripped logcat of when trying to activate Mobile Payment
```
03-22 11:17:32.534 14286 14286 W libc    : Access denied finding property "odsign.verification.success"
03-22 11:17:32.530 14286 14286 W tatementservice: type=1400 audit(0.0:3158): avc: denied { read } for name="u:object_r:odsign_prop:s0" dev="tmpfs" ino=27318 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:odsign_prop:s0 tclass=file permissive=0 app=com.android.statementservice
03-22 11:17:32.537 14286 14286 W com.android.statementservice: ART APEX data files are untrusted.
03-22 11:17:32.533 14286 14286 W tatementservice: type=1400 audit(0.0:3159): avc: denied { lock } for path="/apex/com.android.art/javalib/arm64/boot.art" dev="dm-8" ino=150 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.android.statementservice
03-22 11:17:32.537 14286 14286 W tatementservice: type=1400 audit(0.0:3160): avc: denied { lock } for path="/apex/com.android.art/javalib/arm64/boot-core-libart.art" dev="dm-8" ino=144 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.android.statementservice
03-22 11:17:32.537 14286 14286 W tatementservice: type=1400 audit(0.0:3161): avc: denied { lock } for path="/apex/com.android.art/javalib/arm64/boot-okhttp.art" dev="dm-8" ino=147 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.android.statementservice
03-22 11:17:32.537 14286 14286 W tatementservice: type=1400 audit(0.0:3162): avc: denied { lock } for path="/apex/com.android.art/javalib/arm64/boot-bouncycastle.art" dev="dm-8" ino=141 scontext=u:r:platform_app:s0:c512,c768 tcontext=u:object_r:system_file:s0 tclass=file permissive=0 app=com.android.statementservice
03-22 11:17:32.623 14286 14286 D com.android.statementservice: Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
03-22 11:17:32.623 14286 14286 D com.android.statementservice: I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt68l.dat
03-22 11:17:32.648 14286 14286 D ProcessState: Binder ioctl to enable oneway spam detection failed: Invalid argument
03-22 11:17:32.705  1464  3886 D CompatibilityChangeReporter: Compat change id reported: 168419799; UID 10087; state: DISABLED
03-22 11:17:32.709 14286 14312 W libc    : Access denied finding property "qemu.sf.lcd_density"
03-22 11:17:32.709 14286 14312 W libc    : Access denied finding property "qemu.sf.lcd_density"
03-22 11:17:32.718 14286 14286 D CompatibilityChangeReporter: Compat change id reported: 171979766; UID 10087; state: DISABLED
03-22 11:17:32.757 14286 14286 I PackageParsing: Skipping target and overlay pair com.android.settings and /product/overlay/SettingsOverlayG025M.apk: overlay ignored due to required system property: ro.boot.hardware.sku with value: G025M
03-22 11:17:32.760 14286 14286 I PackageParsing: Skipping target and overlay pair com.android.settings and /product/overlay/SettingsOverlayG025J.apk: overlay ignored due to required system property: ro.boot.hardware.sku with value: G025J
03-22 11:17:32.823 14286 14315 D CompatibilityChangeReporter: Compat change id reported: 160794467; UID 10087; state: DISABLED
03-22 11:17:32.825  1464  3886 D CompatibilityChangeReporter: Compat change id reported: 171306433; UID 10087; state: DISABLED
03-22 11:17:32.884  1464  1817 D ConnectivityService: requestNetwork for uid/pid:10087/14286 activeRequest: null callbackRequest: 264 [NetworkRequest [ REQUEST id=265, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10087 RequestorUid: 10087 RequestorPkg: com.android.statementservice] ]] callback flags: 0 priority: 2147483647
03-22 11:17:32.887  1464  2080 D ConnectivityService: NetReassign [265 : null → 100]
03-22 11:17:32.897  1464  2063 D WifiNetworkFactory: got request NetworkRequest [ REQUEST id=265, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10087 RequestorUid: 10087 RequestorPkg: com.android.statementservice] ]
03-22 11:17:32.898  1464  2063 D UntrustedWifiNetworkFactory: got request NetworkRequest [ REQUEST id=265, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10087 RequestorUid: 10087 RequestorPkg: com.android.statementservice] ]
03-22 11:17:32.899  1464  2063 D OemPaidWifiNetworkFactory: got request NetworkRequest [ REQUEST id=265, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10087 RequestorUid: 10087 RequestorPkg: com.android.statementservice] ]
03-22 11:17:32.952 14286 14315 E AndroidRuntime: FATAL EXCEPTION: pool-2-thread-1
03-22 11:17:32.952 14286 14315 E AndroidRuntime: Process: com.android.statementservice, PID: 14286
03-22 11:17:32.952 14286 14315 E AndroidRuntime: java.lang.IllegalStateException: Data cannot occupy more than 10240 bytes when serialized
03-22 11:17:32.952 14286 14315 E AndroidRuntime: 	at androidx.work.Data.toByteArrayInternal(Data.java:417)
03-22 11:17:32.952 14286 14315 E AndroidRuntime: 	at androidx.work.Data$Builder.build(Data.java:846)
03-22 11:17:32.952 14286 14315 E AndroidRuntime: 	at androidx.work.OverwritingInputMerger.merge(OverwritingInputMerger.java:44)
03-22 11:17:32.952 14286 14315 E AndroidRuntime: 	at androidx.work.impl.WorkerWrapper.runWorker(WorkerWrapper.java:227)
03-22 11:17:32.952 14286 14315 E AndroidRuntime: 	at androidx.work.impl.WorkerWrapper.run(WorkerWrapper.java:137)
03-22 11:17:32.952 14286 14315 E AndroidRuntime: 	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
03-22 11:17:32.952 14286 14315 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
03-22 11:17:32.952 14286 14315 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
03-22 11:17:32.952 14286 14315 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:920)
03-22 11:17:32.957  1464 14322 I DropBoxManagerService: add tag=system_app_crash isTagEnabled=true flags=0x2
03-22 11:17:32.958 14286 14315 I Process : Sending signal. PID: 14286 SIG: 9
03-22 11:17:32.962  1464  1663 W BroadcastQueue: Permission Denial: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to ProcessRecord{43a8aab 3073:com.google.android.gms.persistent/u0a164} (pid=3073, uid=10164) requires android.permission.READ_LOGS due to sender android (uid 1000)
03-22 11:17:32.963  1464  1663 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
03-22 11:17:32.963  1464  1663 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
03-22 11:17:32.995  1464  1817 I ActivityManager: Process com.android.statementservice (pid 14286) has died: cch+5 CEM 
03-22 11:17:32.996  1464  1672 I libprocessgroup: Successfully killed process cgroup uid 10087 pid 14286 in 0ms
03-22 11:17:32.997   835   835 I Zygote  : Process 14286 exited due to signal 9 (Killed)

```

**Comment by akc3n** [comment]
Thank you very much @ljrk0

**Comment by Z0pyrus** [comment]
Any chances that the mobile payment is working now @ljrk0  ?

**Comment by ljrk0** [comment]
@Z0pyrus Thanks for the heads-up!  Indeed, I tried now, and I could successfully activate mobile payment.  However, I didn't have any chance to try it.  I will come back to this later :)

**Comment by robovoice1** [comment]
https://www.kuketz-blog.de/nfc-datenschutzfreundlich-bezahlen-mit-dem-android-phone/

**Comment by spring-onion** [comment]
This app requires to be installed from the play store, it refuses to launch otherwise. It warns you that you are using something abnormal so possible play integrity is tripped or otherwise determined; doesn't seem to affect functionality, can just hit continue.
